name: Build core
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
    tags:
      - 'v*.*.*'
    paths:
      - src/**
      - frontend/**
      - terraform/application/**
      - pom.xml
      - Dockerfile
      - .github/workflows/build_core.yaml

jobs:
  compile-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: 25
          distribution: corretto
          cache: maven

      - name: Unit tests
        run: ./mvnw package test

      - name: Upload jar artifact
        uses: actions/upload-artifact@v4
        with:
          name: grammr-core-jar
          path: target/grammr-core-1.0-SNAPSHOT.jar

  integration-test:
    name: Integration tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: 25
          distribution: corretto
          cache: maven

      - name: Set up local environment
        run: |
          docker compose -f local/docker-compose.yaml up -d --remove-orphans --wait
          cd local/expectations && python set_expectations.py

      - name: Run integration tests
        run: |
          ./mvnw package test -P integration

  frontend-tests:
    name: Frontend tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          cache-dependency-path: frontend/pnpm-lock.yaml
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        working-directory: frontend
        run: pnpm install

      - name: Run eslint
        working-directory: frontend
        run: pnpm run lint:strict

      - name: Run typechecks
        working-directory: frontend
        run: pnpm run typecheck

      - name: Run frontend tests
        working-directory: frontend
        run: pnpm run test

  build-frontend:
    name: Build grammr-frontend Docker image
    runs-on: ubuntu-latest
    needs: [ frontend-tests, compile-and-test, integration-test ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        id: docker-metadata
        uses: docker/metadata-action@v5
        with:
          images: grammrapp/grammr-frontend
          flavor: |
            latest=true
          tags: |
            type=semver,pattern={{version}}-prod
            type=raw,value={{branch}}-{{date 'YYYYMMDDHHmmss' tz='UTC'}}-{{sha}}
            type=sha

      - name: Determine publishable key
        id: publishable-key
        working-directory: frontend
        run: |
          source publishable-keys
          if [ "${GITHUB_REF##*/}" = "main" ]; then
            echo "key=$NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY_MAIN" >> $GITHUB_OUTPUT
          else
            echo "key=$NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY_DEVELOP" >> $GITHUB_OUTPUT
          fi

      - name: Build and push
        uses: docker/build-push-action@v5
        env:
          NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ steps.publishable-key.outputs.key }}
        with:
          build-args: |
            NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${{ env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
          context: ./frontend
          file: ./frontend/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.docker-metadata.outputs.tags }}
          labels: ${{ steps.docker-metadata.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max


  build-grammr-core:
    name: Build grammr-core Docker image
    runs-on: ubuntu-latest
    needs: [ compile-and-test, integration-test, frontend-tests ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Download jar
        uses: actions/download-artifact@v4
        with:
          name: grammr-core-jar
          path: target/

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        id: docker-metadata
        uses: docker/metadata-action@v5
        with:
          images: grammrapp/grammr-core
          flavor: |
            latest=true
          tags: |
            type=semver,pattern={{version}}
            type=raw,value={{branch}}-{{date 'YYYYMMDDHHmmss' tz='UTC'}}-{{sha}}
            type=sha

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.docker-metadata.outputs.tags }}
          labels: ${{ steps.docker-metadata.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy-swagger:
    runs-on: ubuntu-latest
    needs: [ build-grammr-core ]
    name: Deploy Swagger UI to Github Pages
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '25'

      - name: Build and run Spring Boot app
        run: |
          docker compose -f local/docker-compose.yaml up postgresql -d
          ./mvnw clean package -DskipTests
          OPENAI_API_KEY=some-test-key mvn spring-boot:start -Dspring-boot.run.profiles=local

      - name: Fetch OpenAPI spec
        run: |
          curl http://localhost:8080/v3/api-docs > openapi.json

      - name: Kill Spring Boot app
        run: |
          mvn spring-boot:stop

      - name: Generate Swagger UI
        run: |
          mkdir swagger-ui
          curl -L https://github.com/swagger-api/swagger-ui/archive/refs/heads/master.zip -o swagger-ui.zip
          unzip swagger-ui.zip
          mv swagger-ui-master/dist/* swagger-ui/
          cp openapi.json swagger-ui/
          sed -i 's|https://petstore.swagger.io/v2/swagger.json|openapi.json|g' swagger-ui/swagger-initializer.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./swagger-ui
